### ISSUE TITLE
🚀 : Better Footer Design

### ISSUE THREAD

**Issue by xuelink** [langxapp/website#48]
**Is your feature request related to a problem? Please describe.**
The current footer design lacks clarity and organization, making it difficult for users to navigate and find relevant information easily.

**Describe the solution you'd like**
Implement a better footer design that clearly categorizes sections such as Product, Learn, Resources, and About. Each category should be easily distinguishable and clickable, leading users to the respective sections of the website.

**Describe alternatives you've considered**
One alternative could be to revamp the entire website layout, including the footer, to ensure a more cohesive user experience. However, a focused improvement on the footer alone might be a quicker and more targeted solution.

**Additional context**
Attached is some example screenshots illustrating the desired footer design.

<img width="1730" alt="Screenshot 2024-04-12 at 12 29 11 PM" src="https://github.com/langxapp/website/assets/3280475/65222861-5bec-4b64-b40d-775f90cbfec0">

<img width="1786" alt="Screenshot 2024-04-12 at 12 37 07 PM" src="https://github.com/langxapp/website/assets/3280475/08b41760-1e6a-4e06-bfe3-7c56235844b7">

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by xuelink** [comment]
should be added.
- [ ] Token (token.langx.io)
- [ ] Insight (insight.langx.io)

**Comment by xuelink** [comment]
@jakebogan01 i think you can deal with this issue as well :)

**Comment by jakebogan01** [comment]
@xuelink Yeah, no problem I can take care of this one as well.

**Comment by xuelink** [comment]
> @xuelink Yeah, no problem I can take care of this one as well.

@jakebogan01 Thank you very much !

**Comment by xuelink** [comment]
@jakebogan01 As a reminder, please test it with mobile version and narrow browser as well, its kind of tricky when you are doing it :) Let me know if need any help or further questions, thank you !

**Comment by jakebogan01** [comment]
@xuelink Thanks for the tips, I'll try my best to make sure the new footer design update looks good

**Comment by jakebogan01** [comment]
@xuelink I created a [PR](https://github.com/langxapp/website/pull/55) let me know what you think

**Comment by xuelink** [comment]
Hey @jakebogan01,

I hope you're doing well! I've been thinking about our website lately, and I'm really excited about the idea of creating a **v0.3** version with a fresh perspective. I believe there's so much potential to enhance the user experience and overall aesthetics.

I'd like to propose a collaborative effort where you can take the lead on redesigning all the components from your unique viewpoint. Your creativity and expertise could truly breathe new life into our website.

To facilitate this process, I'm more than happy to grant you admin rights to the repository. This will give you the freedom to work on a new branch and implement your vision without any constraints.

I understand that you're familiar with the general structure and functionalities of the website, which will undoubtedly expedite the development process.

Let's embark on this journey together and create something remarkable. Your input and dedication will be invaluable in shaping the future of our online presence.

Looking forward to hearing your thoughts and kicking off this exciting project!

**Comment by jakebogan01** [comment]
@xuelink Thank you for the offer, I am honored to be apart of the journey. I would like to help continue to improve the success and growth of the site. I will try me best to spare as much spare time I can and help with the front-end redesign.

I would like to point out a few things. I'm not sure if you are aware of [Tailwind CSS](https://tailwindcss.com/), it is a common and most popular utility CSS framework that I would highly recommend to use in the v0.3 of your site (only if you approve of course). 

It makes the styling much quicker and cleaner. Also, you can combine this with a UI library such as [Skeleton UI](https://www.skeleton.dev/). Skeleton UI only works with Sveltekit and is an amazing UI made with Tailwind CSS. Although it might be a hit or miss trying to implement it into an already existing project. Usually you are meant to create a new project built by Skeleton. However, it is still possible to implement itself into existing projects.

With that being said, if you choose to not use Tailwind, that is 100% fine. I can help maybe create a few mockup redesigns of the website and we can collaborate on changes to be made before I implement them into the code myself.

**Comment by xuelink** [comment]
> @xuelink Thank you for the offer, I am honored to be apart of the journey. I would like to help continue to improve the success and growth of the site. I will try me best to spare as much spare time I can and help with the front-end redesign.
> 
> I would like to point out a few things. I'm not sure if you are aware of [Tailwind CSS](https://tailwindcss.com/), it is a common and most popular utility CSS framework that I would highly recommend to use in the v0.3 of your site (only if you approve of course).
> 
> It makes the styling much quicker and cleaner. Also, you can combine this with a UI library such as [Skeleton UI](https://www.skeleton.dev/). Skeleton UI only works with Sveltekit and is an amazing UI made with Tailwind CSS. Although it might be a hit or miss trying to implement it into an already existing project. Usually you are meant to create a new project built by Skeleton. However, it is still possible to implement itself into existing projects.
> 
> With that being said, if you choose to not use Tailwind, that is 100% fine. I can help maybe create a few mockup redesigns of the website and we can collaborate on changes to be made before I implement them into the code myself.

@jakebogan01 Tailwind CSS library is indeed very successful and widely used, feel free to use it. No issues, no problem. It would be great for me to get experience and learn about tailwind through this process as well. Additionally, benefiting from your knowledge will surely accelerate and guide us. Thank you!

**Comment by xuelink** [comment]
@jakebogan01 Ok, feel free and its also ok to convert them all if needs, no worries! You have a part of `website` Team here now which has `write` permissions for [website](https://github.com/langxapp/website) & [token-website](https://github.com/langxapp/token-website) and all future web related repos. So you can feel free to make any changes if you want, i had a chance to take a look your portfolio, they looks awesome. Congrats!

**Comment by jakebogan01** [comment]
@xuelink Thank you, I'll do my best

**Comment by xuelink** [comment]
Also, we can move out blog to Medium? @pizofreude suggests that it's time to open a Medium page and migrate our blog there. What do you think @jakebogan01 ? It makes this repo more comfortable to work if we wont have inline blog feature, but at the same time, its not helpful for SEO, i dont know :) What do you suggest ?

**Comment by jakebogan01** [comment]
@xuelink just to make sure I understand, your thinking of making a separate page or website for the blog?

**Comment by xuelink** [comment]
@jakebogan01 I mean to make outsource blog here: https://medium.com/ or keep it within the webpage as we currently have

**Comment by jakebogan01** [comment]
@xuelink Oh okay. I'm not really sure, personally I never made nor owned a blog nor managed a business blog before, so I wouldn't know the best company strategic strategy to go with to be honest.

**Comment by pizofreude** [comment]
I would highly advice to maintain our current subdirectory blog: https://langx.io/blog/ and only create a new subdomain and linked it to Medium when we create an official one for LangX. This does two things: Keep current SEO and improve it via the new subdomain re: blog.langx.io for our official Medium blog. It would be very intuitive if we can add auto-publish from our subdirectory blog to our subdomain blog. I know this feature is available as plugin in Wordpress. However, Angular is totally new tool for me and currently I'm not well-versed on how to implement it. For blog structure with SEO optimization, my proposal is still WIP (not enough time to work on it now, need to clear more on my pipeline).

**Comment by xuelink** [comment]
I like that idea to keep up with both of them. Automation is no problem i can donit but is there any danger zone here because im worried about SEO, google spiders may decrease our website value because we have duplicate content with Medium? 🤷🏻‍♂️ 

When we add backlink within Footer section then it may work perfectly as you said @pizofreude

**Comment by pizofreude** [comment]
Regarding SEO for republishing blog content from our subdirectory to subdomain, I have seen many companies do it. If memory recalls correctly, we have someone from our Discord who is a master SEO. I can't recall his/her name though. Do you know who I'm referring to?
Otherwise, here's what my quick AI companion aide have to say about it:

Republishing content from your website's subdirectory to a Medium subdomain can indeed have implications for SEO, particularly concerning duplicate content. Here are some key points to consider:

- **Duplicate Content**: Google's algorithms are designed to avoid showing multiple versions of the same content. If the same content appears on both your subdirectory and Medium subdomain, Google may filter one out of the search results¹².
- **Canonical Tags**: To mitigate the risk of duplicate content penalties, you can use canonical tags. A canonical tag tells search engines which version of the content is the "master" or original. You can set the canonical URL to your original blog post on your subdirectory, indicating to search engines that the Medium post is a duplicate and the original content is on your site¹².
- **SEO Impact**: Subdomains are often treated as separate entities by search engines, meaning any link equity and authority built by your content on Medium may not directly benefit your main domain. Conversely, content in a subdirectory is more closely tied to the main domain's SEO metrics¹².
- **Content Strategy**: If SEO is a priority, consider whether republishing on Medium aligns with your overall content strategy. Medium can be a great platform for reaching a new audience, but if the goal is to strengthen your site's SEO, keeping content within your subdirectory may be more beneficial².

In summary, while republishing to Medium can help with visibility and reaching a broader audience, it's important to carefully manage the SEO aspects to ensure that your website's value isn't diminished due to duplicate content issues. Using canonical tags and considering the strategic goals of your SEO and content marketing efforts will be crucial in navigating this potential danger zone¹²³.

Source: Conversation with Bing, 4/[1](https://blog.hubspot.com/marketing/subdomain-vs-subdirectory)8/[2](https://www.seo.com/blog/subdomains-for-seo/)024
(1) Subdomain or Subdirectory? What They Are & How They Affect SEO. https://blog.hubspot.com/marketing/subdomain-vs-subdirectory.
(2) Subdomains for SEO: Should You Use Them? Why & Why Not. https://www.seo.com/blog/subdomains-for-seo/.
(3) New Writer’s Crash Course #[2](https://www.seo.com/blog/subdomains-for-seo/): Subdirectory or Subdomain? - Medium. https://medium.com/new-writers-welcome/new-writers-crash-course-2-subdirectory-or-subdomain-2c4d5a89a720.

May **Canonical Tags** be in our force.

**Comment by xuelink** [comment]
@pizofreude OK, i got the point. If you remember that you see some of the companies do blog for both, its ok, no need to overthinking about it aha. Besides that, i remember that SEO Guy but i dont want to ping him, he is trying to start a new career in US so nowadays he is super busy. It's ok, Medium is the best for blogging and SEO as well but we should have enterprise solution i think. it costs 5bucks a month :D

**Comment by pizofreude** [comment]
> we should have enterprise solution

Custom domain and blog repost automation isn't really necessary for now. We can opt for the free tier Medium and manually republish the canonical link there. Once we hit >5 blogs weekly basis, then we'll think about the enterprise solution.

**Comment by xuelink** [comment]
> Once we hit >5 blogs weekly basis, then we'll think about the enterprise solution.

@pizofreude Sounds great! But can't open any publicitaions with a free tier, it redirects to https://medium.com/plans

<img width="524" alt="Screenshot 2024-04-19 at 2 12 04 PM" src="https://github.com/langx/website/assets/3280475/55fced09-6340-4b74-8b69-a4dfcf4df9e8">

**Comment by xuelink** [comment]
By the way, i liked the design of [lingq.com](https://lingq.com) , it reminds me [duolingo.com](https://duolingo.com).

You are free to do but its just for your information @jakebogan01

**Comment by xuelink** [comment]
@jakebogan01 fixed with this commit: https://github.com/langx/website/commit/1d14b562c8a303fcfa69e2296509594913f61069

https://github.com/langx/website/assets/3280475/48a7ef42-8038-4c0f-9897-902f5538667c

**Comment by jakebogan01** [comment]
@xuelink thanks for fixing that, didn't see that issue myself

**Comment by xuelink** [comment]
<img width="438" alt="Screenshot 2024-04-21 at 4 54 27 PM" src="https://github.com/langx/website/assets/3280475/0d9dedcd-a55b-43e1-a08d-6c7c2497cb16">

@jakebogan01 i coudn't centered second line, if you are able to do, appriciated :)

**Comment by jakebogan01** [comment]
@xuelink no worries I'll look into it
